### ISSUE TITLE
Unable to download hdf5 file

### ISSUE THREAD

**Issue by ManjeeraJagiri** [rykov8/ssd_keras#100]
![error](https://user-images.githubusercontent.com/30171457/29447603-4964c654-8410-11e7-8ca1-7ab949f2f95b.PNG)
The site is not opening and I receive the following error

**Comment by Stanpol** [comment]
Here is a link to Google drive: https://drive.google.com/drive/folders/0B2_-RUtcPduOMDRIWC1wNm1ZOXM?usp=sharing

**Comment by ManjeeraJagiri** [comment]
Thanx a lot!
