### ISSUE TITLE
Error using tensorflow 1.4.1

### ISSUE THREAD

**Issue by sudonto** [rykov8/ssd_keras#129]
I have error running SSD_training.ipynb. This is the error message:

> TypeError: l2_normalize() got an unexpected keyword argument 'axis'

My spesification is Keras 2.0, Tensorflow 1.4.1. But, when I run SSD_training.ipynb using Tensorflow 1.6, No error occured. At the moment, I have to use Tensorflow 1.4.1. 

Thank you.

**Comment by sudonto** [comment]
Ok, already fix it. Closed.

**Comment by MAGI003769** [comment]
Hi, could you please tell me how to solve this? I met the same problem.
Our server runs TensorFlow 1.4.0

**Comment by sudonto** [comment]
Hi, if I remember correctly, there is a syntax that I changed in _tensorflow_backend.py_ in _backend_ folder. Please make a comparison between the version of Tensorflow you are using and Tensorflow 1.6.
