### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by lechatthecat** [rykov8/ssd_keras#131]
I changed the dataset and ran the SSD_training.ipynb.
I keep getting this error.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-96-8b2c268315d5> in <module>()
      1 for i, img in enumerate(images):
      2     # Parse the outputs.
----> 3     det_label = results[0][:, 0]
      4     det_conf = results[0][:, 1]
      5     det_xmin = results[0][:, 2]

TypeError: list indices must be integers or slices, not tuple

How can I remove this error?

**Comment by logoman04** [comment]
How did you remove this error?

**Comment by lechatthecat** [comment]
It was because pkl file wasn't made properly. I re-created the pkl file and training worked without problems.

**Comment by logoman04** [comment]
Why is this issue related to any pkl file? This error occurs during prediction. 
Additionally, if it is a pkl file issue, what was the issue? As in, how was it made incorrectly?

**Comment by lechatthecat** [comment]
For me, the problem was the num of classes. It was wrong value.   
I followed this instruction:
https://noteoneverything.blogspot.com/2018/03/single-shot-multibox-detector-how-to.html
