### ISSUE TITLE
Does the MIT LICENSE also apply to the trained weights?

### ISSUE THREAD

**Issue by lunardog** [rykov8/ssd_keras#16]
First of all, thank you for your work and helping with all the issues. 

I want to use the code commercially. Does the MIT license in `LICENSE` apply to the code only or also the downloadable weights? If not, what is the license on the weights?

**Comment by rykov8** [comment]
Thanks for your feedback!
Actually, I cannot say, that I'm familiar with this licensing stuff, MIT was the default option when I created the repo and I left it. The weights are ported from the original ones, and if it matters, then probably the license is the same as in [the original repo](https://github.com/weiliu89/caffe/tree/ssd), that also seems to be some kind of MIT license. If it doesn't matter, and the license on the weight depends on me, then let it be MIT as in the repo.
To make long story short, I think you can use the weights in any application.

**Comment by lunardog** [comment]
Great thanks.
