### ISSUE TITLE
assign_boxes method may have a bug

### ISSUE THREAD

**Issue by sonnyhu** [rykov8/ssd_keras#17]
Hi,

Thanks for the great work!

When I tried to run the training script, ran into shape mismatch at this line: https://github.com/rykov8/ssd_keras/blob/master/ssd_utils.py#L149

Should `assignment[:, 5:-8][best_iou_mask]`  be `assignment[:, 4:-8][best_iou_mask]`?

**Comment by rykov8** [comment]
@sonnyhu Hi! No, it shouldn't. `assignment[:, 4]` is responsible for special background class and `assignment[:, 5:-8]` stores the information about real classes. Probably, your ground truth format is not as expected? Could you, please, provide more information about your error?

**Comment by sonnyhu** [comment]
@rykov8 I was trying to train it with 3 classes. Maybe this is where the problem is? I have not figured out what I should change except for `NUM_CLASSES`. I think I am missing something.

Thanks!

**Comment by rykov8** [comment]
@sonnyhu probably, you need [this comment](https://github.com/rykov8/ssd_keras/issues/15#issuecomment-265250161), `NUM_CLASSES` is equal to the actual number of classes + 1 auxiliary background class.

**Comment by sonnyhu** [comment]
@rykov8 Got it. I looked at that comment yesterday but I definitely missed `NUM_CLASSES` is actually number of classes + 1. Thanks. Let me try it out and report back.
