### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by zhanghan328** [rykov8/ssd_keras#24]
I just want to detect the fish and capture it from a image.  One picture only contain one kind of fish. My dataset has 7 kinds of fishes image.   How to train my dataset and i can capture fish from a  image.   Thanks.

**Comment by rykov8** [comment]
Please, see [`SSD_training.ipynb`](https://github.com/rykov8/ssd_keras/blob/master/SSD_training.ipynb).

**Comment by nixingyang** [comment]
@zhanghan328 Hi, I suppose that you are working on the Kaggle competition. How is your progress with this SSD algorithm? From my experiment, the model suffered a lot from over-fitting and it could not detect fishes in the validation/testing dataset.
