### ISSUE TITLE
link to weights dead

### ISSUE THREAD

**Issue by OlivierML** [rykov8/ssd_keras#46]
Hello,
it seems the Mega link for downloading the weights is dead. 
Are you planning on making a new one?

Thanks for your work!

**Comment by rykov8** [comment]
@OlivierML sorry, but it works for me at least in Safari's private mode (thus I am not logged in).

**Comment by oarriaga** [comment]
@OlivierML I also checked and is working for me with google chrome.

**Comment by OlivierML** [comment]
My bad, The issue comes from my side.
Thanks!
