### ISSUE TITLE
Train Problem: Freeze progress bar

### ISSUE THREAD

**Issue by fortunto2** [rykov8/ssd_keras#75]
Hi, i try to train
prepare test datasets
with 20-30 images

But there is no progress, only the number of 1 epoch
on gpu (1080) and cpu same
keras '1.2.2'
tf 1.0.1
 
![2017-04-24 01-44-06](https://cloud.githubusercontent.com/assets/1236751/25317295/88aec63e-288f-11e7-8600-d9cb42312c46.png)

**Comment by fortunto2** [comment]
gpu loaded 0%

![2017-04-24 01-58-04](https://cloud.githubusercontent.com/assets/1236751/25317403/8076bfe2-2891-11e7-9cce-b7109e25dec2.png)

**Comment by rykov8** [comment]
@fortunto2 sorry, no idea what's wrong

**Comment by fortunto2** [comment]
wrong our dataset.. fixed

**Comment by aishanou** [comment]
@fortunto2 what was the fix? I am facing the same issue. No progress even though no error message.
