### ISSUE TITLE
Training on new dataset: Incompatible shapes

### ISSUE THREAD

**Issue by lhk** [rykov8/ssd_keras#78]
I would like to train this network on a custom dataset.

I've created a folder of images. They all have the same size, of 512 x 384 x 3 (width, height, colors)
And a pickled dictionary which contains the image names as keys and numpy arrays as values. Each numpy array has the shape (#objects in image, 7). Where the 7 is x, y, w, h, prob1, prob2, prob3, since there are 3 types of objects in my dataset.

The training_ssd.ipynb has been edited to the new input shape, and pointed to the image directory and the new pickled ground truth.

This produces an error during training:
```
InvalidArgumentError: Incompatible shapes: [16,7308,4] vs. [16,15342,4]
	 [[Node: sub_2 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](strided_slice_20, strided_slice_21)]]
	 [[Node: mul_11/_331 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_181_mul_11", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

I'm using Keras 1.2.2.
I've tested both input shape (384, 512, 3) and (512, 384, 3) since I was unsure if opencv might mix up the dimensions.

I don't know how to fix this.
The model is built without problems, this only occurs during training.
Here is a model.summary()
https://pastebin.com/KmdFm2sW

**Comment by lhk** [comment]
@rykov8 Do I have to update the prior boxes if I want to train on a new input shape ?

**Comment by lhk** [comment]
I've now resized my data. It is training.
So this is really about the boxes.
I'll close the issue, since this is not really a bug in the code.

Thank you for making this code available.

**Comment by skyzhao3q** [comment]
@lhk Could you tell me what size is available ? I am going to train the network with my custom dataset too.
