### ISSUE TITLE
How to create prior_boxes_ssd300.pkl?

### ISSUE THREAD

**Issue by htamakos** [rykov8/ssd_keras#81]
How to create [this pkl file](https://github.com/rykov8/ssd_keras/blob/master/prior_boxes_ssd300.pkl) ?

**Comment by oarriaga** [comment]
please refer to this [issue](https://github.com/rykov8/ssd_keras/issues/52)

**Comment by htamakos** [comment]
@oarriaga 
Oh, I missed it... Thanx 😀
