### ISSUE TITLE
pretrained VGG model

### ISSUE THREAD

**Issue by mks0601** [rykov8/ssd_keras#9]
hi did you use pretrained VGG model? Then how did you subsample the parameter from fc6 and fc7?

**Comment by rykov8** [comment]
The weights are directly ported from `Caffe` weights, provided by the authors in their repo. Check [preparation](https://github.com/weiliu89/caffe/tree/ssd#preparation) part of their README to find the initial pretrained weights. Actually, this weights are taken from [this paper](https://arxiv.org/abs/1506.04579).
