### ISSUE TITLE
Number of prior boxes not corresponding to the paper

### ISSUE THREAD

**Issue by oarriaga** [rykov8/ssd_keras#92]
Hello,
The pickle file provided with the prior boxes has dimensions (7308, 8). However, the number of prior boxes mentioned in the paper for the 300x300 SSD architecture is 8732 boxes. Is this a mistake or maybe a previous version of the SSD architecture?
Thank you again, and sorry for being to picky I am just trying to get the same results as in the paper since I am now calculating the mAP score.

**Comment by D3lt4lph4** [comment]
Hi,

If not too late, you probably want to have a look here #42

**Comment by oarriaga** [comment]
Hello,
Thanks I saw it and forgot to close this issue :)
